[telegram]
token = "1495210700:AAGs57yTIw3Ot0nTWS7XI4BMRdnrSt-1ARQ"
workers = 1
admins = [957539786]
admins_only = false
maintenance_mode = false
persistent_temp_data = true

[sqlite]
filename = "stickersbot.sqlite"

[bot]
sourcecode = ""
issues = ""
