[telegram]
token = "1243339189:AAGFVwjqLA2xyL12i8GOI_nulmBwfYL1E8c"
workers = 1
admins = [957539786]
admins_only = true
maintenance_mode = false
persistent_temp_data = true

[sqlite]
filename = "stickersbot.sqlite"

[bot]
sourcecode = ""
issues = ""
