[telegram]
token = "936020459:AAG2kpygEgkiA41SdQtuWWU5zhPhDuq-JeU"
workers = 1
admins = [957539786]
admins_only = false
maintenance_mode = false
persistent_temp_data = true

[sqlite]
filename = "stickersbot.sqlite"

[bot]
sourcecode = ""
issues = ""
